nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.9.1.cjs

packageExtensions:
  "@sentry/opentelemetry@*":
    peerDependencies:
      "@opentelemetry/core": "^1.0.0"
      "@opentelemetry/api": "^1.0.0"
      "@opentelemetry/sdk-trace-base": "^1.0.0"
